# Generated by Django 6.1 on 2026-08-11 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_tenantprofile"),
        ("geo", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ownerprofile",
            name="ville",
        ),
        migrations.AddField(
            model_name="ownerprofile",
            name="commune",
            field=models.ForeignKey(
                blank=True,
                help_text="Remplace l'ancien champ libre 'ville'",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owner_profiles",
                to="geo.commune",
            ),
        ),
        migrations.AlterField(
            model_name="ownerprofile",
            name="quartier",
            field=models.ForeignKey(
                blank=True,
                help_text="Remplace l'ancien champ libre 'quartier' (village ou quartier)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owner_profiles",
                to="geo.locality",
            ),
        ),
    ]
