# Generated by Django 6.1 on 2026-08-16 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_ownerprofile_ville_ownerprofile_commune_and_more"),
        ("geo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ownerprofile",
            name="arrondissement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owner_profiles",
                to="geo.arrondissement",
            ),
        ),
        migrations.AddField(
            model_name="ownerprofile",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owner_profiles",
                to="geo.department",
            ),
        ),
    ]
