# Generated by Django 6.1 on 2026-08-08 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_tenantprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('icone', models.CharField(blank=True, help_text='Emoji ou icône courte, ex. 🚿', max_length=10)),
            ],
            options={
                'verbose_name': 'Équipement',
                'verbose_name_plural': 'Équipements',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type_logement', models.CharField(choices=[('chambre', 'Chambre'), ('studio', 'Studio'), ('appartement', 'Appartement'), ('maison', 'Maison'), ('villa', 'Villa'), ('autre', 'Autre')], max_length=20)),
                ('prix', models.DecimalField(decimal_places=0, max_digits=12)),
                ('periodicite', models.CharField(choices=[('mensuel', 'Mensuel'), ('trimestriel', 'Trimestriel'), ('annuel', 'Annuel')], default='mensuel', max_length=20)),
                ('caution', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('chambres', models.PositiveSmallIntegerField(default=1)),
                ('ville', models.CharField(max_length=100)),
                ('quartier', models.CharField(max_length=100)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente_validation', 'En attente de validation'), ('validee', 'Validée'), ('publiee', 'Publiée'), ('refusee', 'Refusée'), ('suspendue', 'Suspendue'), ('louee', 'Louée')], default='brouillon', max_length=30)),
                ('disponibilite', models.CharField(choices=[('disponible', 'Disponible'), ('indisponible', 'Indisponible')], default='disponible', max_length=30)),
                ('motif_refus', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publiee_le', models.DateTimeField(blank=True, null=True)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to='accounts.ownerprofile')),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annonces',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.amenity')),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
            ],
            options={
                'verbose_name': "Équipement d'annonce",
                'verbose_name_plural': "Équipements d'annonce",
                'unique_together': {('annonce', 'amenity')},
            },
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='properties', through='properties.PropertyAmenity', to='properties.amenity'),
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.ImageField(upload_to='properties/')),
                ('principale', models.BooleanField(default=False)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'verbose_name': "Photo d'annonce",
                'verbose_name_plural': "Photos d'annonce",
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
