# Generated by Django 6.1 on 2026-08-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='icone',
            field=models.CharField(blank=True, help_text="Classe d'icône Font Awesome (sans le préfixe fa-solid), ex. fa-shower", max_length=40),
        ),
    ]
