# Generated by Django 6.1 on 2026-08-11 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_tenantprofile"),
        ("geo", "0001_initial"),
        ("properties", "0002_alter_amenity_icone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="ville",
        ),
        migrations.AddField(
            model_name="property",
            name="commune",
            field=models.ForeignKey(
                default="",
                help_text="Remplace l'ancien champ libre 'ville'",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="properties",
                to="geo.commune",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="property",
            name="quartier",
            field=models.ForeignKey(
                help_text="Remplace l'ancien champ libre 'quartier' (village ou quartier)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="properties",
                to="geo.locality",
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["commune"], name="properties__commune_f9df2d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["quartier"], name="properties__quartie_b768d2_idx"
            ),
        ),
    ]
