# Generated by Django 6.1 on 2026-08-08 02:57

import apps.payments.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_tenantprofile'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=10)),
                ('reference', models.CharField(default=apps.payments.models.generer_reference, editable=False, max_length=64, unique=True)),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('successful', 'Réussi'), ('failed', 'Échoué'), ('cancelled', 'Annulé'), ('refunded', 'Remboursé')], default='pending', max_length=20)),
                ('methode', models.CharField(blank=True, choices=[('moov_money', 'Moov Money'), ('mtn_money', 'MTN Money')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='properties.property')),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to=settings.AUTH_USER_MODEL)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements_recus', to='accounts.ownerprofile')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts_debloques', to='properties.property')),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts_debloques', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='payments.payment')),
            ],
            options={
                'verbose_name': 'Contact débloqué',
                'verbose_name_plural': 'Contacts débloqués',
                'unique_together': {('locataire', 'annonce')},
            },
        ),
    ]
