# Generated by Django 6.1 on 2026-08-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="sebpay_transaction_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="payment",
            name="telephone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
