# Generated by Django 6.1 on 2026-08-08 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frais_contact', models.DecimalField(decimal_places=0, default=1000, help_text='Frais de mise en relation locataire → propriétaire, en XOF.', max_digits=10)),
                ('devise', models.CharField(default='XOF', max_length=10)),
                ('moov_money_actif', models.BooleanField(default=True)),
                ('mtn_money_actif', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres plateforme',
                'verbose_name_plural': 'Paramètres plateforme',
            },
        ),
    ]
