# Generated by Django 6.1 on 2026-08-08 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_identifiant', models.CharField(max_length=150)),
                ('action', models.CharField(max_length=100)),
                ('cible', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Journal admin',
                'verbose_name_plural': 'Journal admin',
                'ordering': ['-created_at'],
            },
        ),
    ]
