# Generated by Django 6.1 on 2026-08-11 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Commune",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Commune",
                "verbose_name_plural": "Communes",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Département",
                "verbose_name_plural": "Départements",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Arrondissement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=150)),
                (
                    "commune",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arrondissements",
                        to="geo.commune",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arrondissement",
                "verbose_name_plural": "Arrondissements",
                "ordering": ["nom"],
                "unique_together": {("nom", "commune")},
            },
        ),
        migrations.AddField(
            model_name="commune",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="communes",
                to="geo.department",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="commune",
            unique_together={("nom", "department")},
        ),
        migrations.CreateModel(
            name="Locality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                (
                    "locality_type",
                    models.CharField(
                        choices=[("village", "Village"), ("quartier", "Quartier")],
                        default="quartier",
                        max_length=20,
                    ),
                ),
                (
                    "arrondissement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="localities",
                        to="geo.arrondissement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Village / Quartier",
                "verbose_name_plural": "Villages / Quartiers",
                "ordering": ["nom"],
                "unique_together": {("nom", "arrondissement")},
            },
        ),
    ]
